### PARA TRAER TODOS LOS POST
GET http://localhost:3000/api/posts

### PARA CREAR UN POST
Post http://localhost:3000/api/posts
Content-Type: application/json

{
    "title": "Nuevo Post",
    "content": "posteo",
    "urlLink": "www.url.com"
}

### PARA MODIFICAR POST
PUT http://localhost:3000/api/posts/1

{
    "title": "Nuevo Post",
    "content": "posteo",
    "urlLink": "www.url.com"
}


### PARA ELIMINAR EL POST
DELETE http://localhost:3000/api/posts/1